version: "3"
services:
  postgres:
    image: postgres:9.6.12
    ports:
     - "5432:5432"
    volumes:
     - "$HOME/docker/volumes/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: secret
  exemplo-webapp:
    image: ifpbcjz/dac/exemplo-webapp:0.0.2-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=dac
    depends_on:
      - postgres