version: "3"
services:
  postgres:
    image: postgres:9.6.12
    ports:
     - "5432:5432"
    volumes:
     - "$HOME/docker/volumes/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: secret
  payara:
    image: ifpb/payara:latest
    ports:
      - "8080:8080"
      - "4848:4848"
    volumes:
      - "~/payara/apps:/opt/payara/deployments"